# Site settings
title:       Bartek Dev Blog
email:       your_email@example.com
author:      Bartek Górkowy
description: "Just another dev blog"
baseurl:     ""
url:         "http://bgorkowy.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:    bgorkowy
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
